config/routes.rb
Rails.application.routes.draw do
    devise_for :users

  resources :news
  resources :users
  resources :requests
  namespace :admin do
    resources :users
    resources :news
    resources :activities
  end
  resources :activities
  get 'admin', to: 'admin#index'
  get 'policy', to: 'home#policy'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  attachment :image
  has_many :requests, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
  attachment :image
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :admin_user, only: [:new, :edit]
  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to activities_path, notice: "作成しました"
    else
      flash[:danger] = @activity.errors.full_messages
      @activity = Activity.new(activity_params)
      redirect_to new_activity_path
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def destroy
    activity = Activity.find(params[:id])
      activity.destroy
      redirect_to admin_activities_path, notice: '削除しました。'
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    if @activity.save
      redirect_to activities_path, notice: "更新しました"
    else
      flash[:danger] = @activity.errors.full_messages
      @activity = Activity.new(activity_params)
      redirect_to edit_activity_path
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :body, :price, :time, :price_for_child, :price_for_one, :display, :image)
  end

  def admin_user
    redirect_to(new_user_session_path) unless user_signed_in? && current_user.admin
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin_user
  def index
  end

  private
  def admin_user
    redirect_to(new_user_session_path) unless user_signed_in? && current_user.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @newses = News.all.order(created_at: "DESC")
    @activities = Activity.where(display: true)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :admin_user, only: [:new, :edit]
  def index
    @newses = News.all
  end

  def show
    @news = News.find(params[:id])
    @newses = News.all
  end

  def edit
    @news = News.find(params[:id])
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to news_path(@news), notice: "更新しました"
    else
      flash[:danger] = @news.errors.full_messages
      @news = News.new(news_params)
      redirect_to new_news_path
    end
  end
  def destroy
    news = News.find(params[:id])
      news.destroy
      redirect_to admin_news_index_path, notice: '部屋を削除しました。'
  end

  def update
    @news = News.find(params[:id])
    @news.update(news_params)
    if @news.save
      redirect_to news_path(@news), notice: "更新しました"
    else
      flash[:danger] = @news.errors.full_messages
      @news = News.new(news_params)
      redirect_to new_news_path
    end
  end

private

  def news_params
    params.require(:news).permit(:title, :body, :image)
  end

  def admin_user
    redirect_to(new_user_session_path) unless current_user.admin?
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :admin_user, only: [:index]
  def index
    @requests = Request.all.order(created_at: "DESC")
    @activities = Activity.all
  end

  def new
    @activities = Activity.where(display: true)
    @request = Request.new
  end

  def create
    @activities = Activity.where(display: true)
    @request = Request.new(request_params)
    if @request.save
      redirect_to root_path, notice: "リクエストが完了しました"
    else
      flash[:danger] = @request.errors.full_messages
      @request = Request.new(request_params)
      render 'new'
    end
  end

  def destroy
    request = Request.find(params[:id])
      request.destroy
      redirect_to requests_path, notice: 'リクエストを削除しました。'
  end

  private

  def request_params
    params.require(:request).permit(:name, :request_date, :people_adult, :people_child, :activity_id, :name, :email, :tel, :message, :address)
  end

  def admin_user
    redirect_to(new_user_session_path) unless user_signed_in? && current_user.admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_user, only: [:new]
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save && current_user.admin == true
      redirect_to admin_users_path
    elsif @user.save
      redirect_to admin_users_path, notice: "更新が完了しました"
    else
      flash[:danger] = @user.errors.full_messages
      redirect_to edit_admin_user_path(@user)
    end
  end
  private
  def user_params
    params.require(:user).permit(:username, :email, :admin)
  end
  def admin_user
    redirect_to(new_user_session_path) unless current_user.admin?
  end
end

app/helpers/activitys_helper.rb
module ActivitysHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1 class="admin_title">管理画面</h1>
  <section class="admin_index">
    <div class="admin_menu">
      <%= link_to admin_activities_path do %>
        <div class="admin_rooms admins">
          <h3>アクティビティ管理画面</h3>
        </div>
      <% end %>
      <%= link_to requests_path do %>
        <div class="admin_reservations admins">
          <h3>予約管理画面</h3>
        </div>
      <% end %>
      <%= link_to admin_users_path do %>
        <div class="admin_users admins">
          <h3>ユーザー管理画面</h3>
        </div>
      <% end %>
      <%= link_to admin_news_index_path do %>
        <div class="admin_news admins">
          <h3>お知らせ管理画面</h3>
        </div>
      <% end %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asobasal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'false' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
      <ul class="headerLeft">
        <li class=navbar-center>
          <%= link_to "アクティビティ", activities_path, data: {"turbolinks" => false} %>
        </li>
      </ul>
      <div class="logo">
        <%= link_to root_path, data: {"turbolinks" => false}  do %>
          <img class="logoImage" src="/assets/logo_w.png" alt="">
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="headerRight">
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </div>
      <% else %>
        <div class="headerRight">
          <%= link_to new_request_path, data: {"turbolinks" => false}  do %>
            <h3>予約問い合わせ</h3>
          <% end %>
        </div>
      <% end %>
    </header>
    <main>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
    </main>
    <footer>
      <div class="footerLeft">
        <a href="https://instagram.com/be_yan_kappa_guide?igshid=qm7fwrm12pzw" target="_blank"><i class="fa fa-instagram fa-3x" aria-hidden="true"></i></a>
        <a href="https://www.facebook.com/profile.php?id=100017020120504" target="_blank"><i class="fab fa-facebook-square fa-3x"></i></a>

        <p class="c">©︎ RyosukeOnishi</p>
      </div>
      <div class="footerCenter">
        <div class="footerOpen footerCenterItem">
          <img class="footerLogoImage" src="/assets/logo_w.png" alt="">
        </div>
      </div>
      <div class="footerRight">
        <h4>Address</h4>
        <p>北海道上川郡下川町</p>
        <p class="c_responsive">©︎ RyosukeOnishi</p>
      </div>
    </footer>


  </body>
</html>

app/views/shared/_error_messages.html.erb
<% flash.each do |message_type, messages| %>
  <% messages.each do |message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>